#!/bin/env bash

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

for f in *.php; do
    if [[ "$f" == testing.php ]]; then
        continue
    fi
    echo "test $f"
    php -c php.ini -f "$f"
done