#!/bin/env bash

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")"

if [[ $# -eq 0 ]]; then
    files=(*.php)
else
    files=("$@")
fi

for f in "${files[@]}"; do
    if [[ "$f" = testing.php ]]; then
        continue
    fi
    echo "test $f"
    php -c php.ini -f "$f"
done