set schema 'pact';

truncate
    _departement,
    _commune,
    _adresse,
    _abonnement,
    _image,
    _signalable,
    _identite,
    _compte,
    _professionnel,
    _offre,
    _changement_etat,
    _restaurant,
    _tag_restauration,
    _tag_restaurant,
    _activite,
    _visite,
    _langue,
    _langue_visite,
    _spectacle,
    _parcattraction,
    _gallerie,
    _visiteur,
    _prive,
    _moyenpaiement,
    _public,
    _membre,
    _signalement,
    _facture,
    _prestation,
    _tarif,
    _option,
    _souscriptionoption,
    _avis,
    _approuve,
    _desapprouve,
    _avis_resto,
    _reponse
restart identity;

