set schema 'pact';

truncate
    _departement,
    _commune,
    _adresse,
    _abonnement,
    _image,
    _signalable,
    _identite,
    _compte,
    _professionnel,
    _offre,
    _restaurant,
    _activite,
    _visite,
    _langue,
    _spectacle,
    _parc_attractions,
    _visiteur,
    _prive,
    _moyen_paiement,
    _public,
    _membre,
    _facture,
    _prestation,
    _tarif,
    _option,
    _avis,
    _avis_resto,
    _reponse,
    _signalement,
    _code_postal,
    _langue_visite,
    _gallerie,
    _changement_etat,
    _souscription_option,
    _juge,
    _tags_restaurant,
    _horaire_ouverture
restart identity;

